#include "JRLTools.h"

#include "Components/CodeFileListComponent.cpp"
#include "Components/LineEndingsConverterComponent.cpp"
#include "Components/ModulariserComponent.cpp"
#include "Components/SpacingGrabber.cpp"
#include "Components/TabsToSpacesComponent.cpp"
#include "Components/ToolComponent.cpp"
#include "Components/TrailingWhitespaceCleanerComponent.cpp"
#include "Misc/CodeFileList.cpp"
#include "Misc/CodeTokeniserFactory.cpp"
#include "Types/CodeTool.cpp"
#include "Types/LineEndingsConverter.cpp"
#include "Types/Modulariser.cpp"
#include "Types/StringLiteralCapitaliser.cpp"
#include "Types/TabsToSpaces.cpp"
#include "Types/TrailingWhitespaceCleaner.cpp"